# Generated by Django 5.2.12 on 2026-03-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("region", models.CharField(max_length=64)),
                ("instance_id", models.CharField(max_length=128)),
                ("instance_name", models.CharField(max_length=255)),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("private_ip", models.CharField(blank=True, max_length=64)),
                ("public_ip", models.CharField(blank=True, max_length=64)),
                ("os_type", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("terminated", "Terminated"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("vpc_id", models.CharField(blank=True, max_length=128)),
                ("subnet_id", models.CharField(blank=True, max_length=128)),
                ("tags_json", models.JSONField(blank=True, default=dict)),
                ("sync_status", models.CharField(default="pending", max_length=32)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="accounts.cloudaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "region", "instance_name"],
                "unique_together": {("account", "instance_id")},
            },
        ),
    ]
