# Generated by Django 5.2.12 on 2026-03-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudinstance",
            name="jumpserver_asset_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="cloudinstance",
            name="jumpserver_sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("synced", "Synced"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="cloudinstance",
            name="last_jumpserver_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
