# Generated by Django 5.2.12 on 2026-03-24 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DNSZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("zone_id", models.CharField(max_length=128)),
                ("zone_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dns_zones",
                        to="accounts.cloudaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["zone_name"],
                "unique_together": {("account", "zone_id")},
            },
        ),
        migrations.CreateModel(
            name="DNSRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_record_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=32)),
                ("value", models.CharField(max_length=512)),
                ("ttl", models.PositiveIntegerField(default=600)),
                ("line", models.CharField(blank=True, max_length=64)),
                ("priority", models.PositiveIntegerField(default=0)),
                ("proxied", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="domain.dnszone",
                    ),
                ),
            ],
            options={
                "ordering": ["zone__zone_name", "name", "type"],
                "unique_together": {("zone", "provider_record_id")},
            },
        ),
    ]
