# Generated by Django 5.2.12 on 2026-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CMDBAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("cloud_account", "Cloud Account"),
                            ("cloud_instance", "Cloud Instance"),
                            ("dns_zone", "DNS Zone"),
                            ("dns_record", "DNS Record"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                ("source_ref", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(default="active", max_length=32)),
                ("labels", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["asset_type", "name"],
                "unique_together": {("asset_type", "source", "source_ref")},
            },
        ),
    ]
