# Generated by Django 5.2.12 on 2026-03-24 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingTagRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("provider", models.CharField(blank=True, max_length=32)),
                ("source_key", models.CharField(max_length=128)),
                (
                    "target_dimension",
                    models.CharField(
                        choices=[("env", "Env"), ("product", "Product")], max_length=16
                    ),
                ),
                ("default_value", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["target_dimension", "name"],
            },
        ),
        migrations.CreateModel(
            name="BillingLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_month", models.CharField(max_length=7)),
                ("billing_date", models.DateField()),
                ("provider", models.CharField(max_length=32)),
                ("product", models.CharField(max_length=128)),
                ("resource_id", models.CharField(max_length=128)),
                ("resource_name", models.CharField(blank=True, max_length=255)),
                ("currency", models.CharField(default="CNY", max_length=16)),
                (
                    "original_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discounted_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "usage_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("usage_unit", models.CharField(default="hour", max_length=32)),
                ("tag_data", models.JSONField(blank=True, default=dict)),
                ("normalized_env", models.CharField(blank=True, max_length=64)),
                ("normalized_product", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_line_items",
                        to="accounts.cloudaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-billing_date", "provider", "product"],
            },
        ),
    ]
