# Generated by Django 5.2.12 on 2026-03-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloudAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("aliyun", "Aliyun"),
                            ("aws", "AWS"),
                            ("cloudflare", "Cloudflare"),
                            ("jumpserver", "JumpServer"),
                        ],
                        max_length=32,
                    ),
                ),
                ("access_key", models.CharField(blank=True, max_length=255)),
                ("secret_key", models.CharField(blank=True, max_length=255)),
                ("extra_config", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
