# Generated by Django 5.2.12 on 2026-03-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_taskexecution_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskexecution",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("account_sync", "Account Sync"),
                    ("dns_sync", "DNS Sync"),
                    ("instance_sync", "Instance Sync"),
                    ("jumpserver_sync", "JumpServer Sync"),
                    ("billing_collect", "Billing Collect"),
                ],
                max_length=32,
            ),
        ),
    ]
