# Generated by Django 5.2.12 on 2026-03-24 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("assets", "0002_cloudinstance_jumpserver_asset_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JumpServerSyncRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("provider", models.CharField(blank=True, max_length=32)),
                ("region", models.CharField(blank=True, max_length=64)),
                ("env", models.CharField(blank=True, max_length=64)),
                ("node_path", models.CharField(blank=True, max_length=255)),
                ("platform", models.CharField(default="linux", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=100)),
                ("extra_config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jumpserver_rules",
                        to="accounts.cloudaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="JumpServerSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumpserver_asset_id", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        default="success",
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jumpserver_sync_logs",
                        to="assets.cloudinstance",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="jumpserver.jumpserversyncrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-synced_at"],
            },
        ),
    ]
